using System;


namespace ArtCenterOnline.Server.Model
{
    public enum SessionStatus
    {
        Planned = 0,
        Completed = 1,
        Cancelled = 2,
        NoShow = 3,
        Rescheduled = 4
    }


    public class ClassSession
    {
        public int SessionId { get; set; } // PK


        public int ClassID { get; set; } // FK -> ClassInfo
        public ClassInfo? Class { get; set; }


        // Giáo viên dạy buổi này: null => mặc định MainTeacher của lớp
        public int? TeacherId { get; set; } // FK -> TeacherInfo
        public TeacherInfo? Teacher { get; set; }


        public DateOnly SessionDate { get; set; } // Ngày học
        public TimeSpan StartTime { get; set; } // Giờ bắt đầu
        public TimeSpan EndTime { get; set; } // Giờ kết thúc


        public string? Note { get; set; }
        public SessionStatus Status { get; set; } = SessionStatus.Planned;


        public bool IsAutoGenerated { get; set; } = true; // true nếu sinh từ lịch mẫu
        public DateTime CreatedAt { get; set; } = DateTime.UtcNow;

        public bool AccountingApplied { get; set; } = false;
        public DateTime? AccountingAppliedAtUtc { get; set; }

    }
}